---
sudo: required
language: python
services:
  - docker

install:
  - pip install molecule docker ansible

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
