---
# handlers file for ossec-server

- name: Restart ossec-server
  ansible.builtin.service:
    name: "{{ ossec_init_name }}"
    state: restarted
    enabled: true

- name: Systemd daemon-reload
  command: systemctl daemon-reload
  tags:
    - skip_ansible_lint
