---
- name: Prepare
  hosts: all
  tasks:
    - name: "Installing tools on CentOS"
      yum:
        pkg:
          - net-tools
          - which
        state: present
      when: ansible_distribution == 'CentOS'

    - name: "Installing tools on NON-CentOS"
      apt:
        name:
          - net-tools
        state: present
      when: ansible_distribution != 'CentOS'
